# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangaloreJobPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_add', models.CharField(max_length=40)),
                ('emp_designation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ChennaiJobPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_add', models.CharField(max_length=40)),
                ('emp_designation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HydJobPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_add', models.CharField(max_length=40)),
                ('emp_designation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PuneJobPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_add', models.CharField(max_length=40)),
                ('emp_designation', models.CharField(max_length=40)),
            ],
        ),
    ]
